# This file does not run on master nodes
---
- name: Nodes - Check if Certificate Authority is available
  become: yes
  stat:
    path: "{{ i2_pki_path }}/trusted_parent.crt"
  register: trusted_authority
  when: i2_connection_allowed

- name: Nodes - Initialize Certificate Directory
  become: yes
  file:
    path: "{{ i2_pki_path }}"
    state: directory
    owner: "{{ i2_user }}"
    group: "{{ i2_group }}"
    mode: 0700

# This command must be run as privileged user or the icinga user.
- name: Nodes - Generate Client Ticket on Master
  become: yes
  command: icinga2 pki ticket --cn {{ i2_hostname }}
  register: pki_ticket
  delegate_to: "{{ configuration_master }}"
  when:
    - i2_certificate_signed_by_ca is sameas false
    - i2_connection_allowed

- name: Nodes - Generate self-signed certificate for first-contact with parent
  become: yes
  command: >
    icinga2 pki new-cert --cn {{ i2_hostname }}
      --key {{ i2_pki_path }}/{{ i2_hostname }}.key
      --cert {{ i2_pki_file }}
  when:
    - i2_connection_allowed
    - trusted_authority.stat.exists is sameas false

- name: Nodes - Retrieve Public Certificate from Parent Node
  become: yes
  command: >
    icinga2 pki save-cert
      --key {{ i2_pki_path }}/{{ i2_hostname }}.key
      --cert {{ i2_pki_file }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --host {{ hostvars[i2_parent_nodes[0]]['i2_hostname'] }}
  when:
    - i2_connection_allowed
    - trusted_authority.stat.exists is sameas false

- name: Nodes - Retrieve signed certificate and set-up agent (Top-Down)
  become: yes
  command: >
    icinga2 node setup
      --cn {{ i2_hostname }}
      --ticket {{ pki_ticket.stdout }}
      --endpoint {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --zone {{ i2_zonename }}
      --parent_zone {{ i2_zone }}
      --parent_host {{ hostvars[i2_peer_nodes[0]]['i2_hostname'] }}
      --accept-commands
      --accept-config
      --disable-confd
  when:
    - i2_connection_allowed
    - i2_connection_direction == 'top-down'
    - not i2_certificate_signed_by_ca
  notify: restart icinga2

- name: Collect endpoints for bottom-up config
  set_fact:
    endpoints: "{{ endpoints|default('') }}
     --endpoint {{ hostvars[item]['i2_hostname'] }},{{ hostvars[item]['i2_api_host'] }},{{ hostvars[item]['i2_api_port'] }}"
  loop: "{{ i2_parent_nodes }}"
  when:
    - i2_connection_allowed
    - i2_connection_direction == 'bottom-up'
    - not i2_certificate_signed_by_ca

- name: Generate client certificate on master
  become: yes
  command: >
    icinga2 pki new-cert --cn {{ i2_hostname }}
    --csr {{ i2_pki_path }}/{{ i2_hostname }}.csr
    --key {{ i2_pki_path }}/{{ i2_hostname }}.key
  delegate_to: "{{ configuration_master }}"
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed

- name: Sign client certificates on master
  become: yes
  command: >
    icinga2 pki sign-csr --csr {{ i2_pki_path }}/{{ i2_hostname }}.csr
    --cert {{ i2_pki_path }}/{{ i2_hostname }}.crt
  delegate_to: "{{ configuration_master }}"
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed

- name: Fetch public ca from master
  fetch:
    src: "{{ i2_pki_path }}/ca.crt"
    dest: buffer/
    flat: yes
  run_once: yes
  delegate_to: "{{ configuration_master }}"
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed

- name: Fetch node certificates from Master
  fetch:
    src: "{{ i2_pki_path }}/{{ item }}"
    dest: buffer/
    flat: yes
  loop: [ "{{ i2_hostname }}.crt", "{{ i2_hostname }}.key" ]
  delegate_to: "{{ configuration_master }}"
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed

- name: Copy ca to node
  copy:
    src: "buffer/ca.crt"
    dest: "{{ i2_pki_path }}/ca.crt"
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed

- name: Copy certificates to respective node
  copy:
    src: "buffer/{{ item }}"
    dest: "{{ i2_pki_path }}/"
  loop: [ "{{ i2_hostname }}.crt", "{{ i2_hostname }}.key" ]
  when:
    - not i2_certificate_signed_by_ca
    - not i2_connection_allowed
  notify: reload icinga2

- name: Ensure state of features on nodes
  become: yes
  shell: >
    icinga2 feature enable {{ item }}
  loop: "{{ i2_alt_features }}"
  when:
    - not i2_connection_allowed

- name: Nodes - Retrieve signed certificate and set-up agent (Bottom-Up)
  become: yes
  command: >-
    icinga2 node setup
      --cn {{ i2_hostname }}
      --ticket {{ pki_ticket.stdout }} {{ endpoints }}
      --trustedcert {{ i2_pki_path }}/trusted_parent.crt
      --zone '{{ i2_zonename }}'
      --parent_zone '{{ i2_parent_zone }}'
      --parent_host {{ hostvars[i2_parent_nodes[0]]['i2_api_host'] }},{{ hostvars[i2_parent_nodes[0]]['i2_api_port'] }}
      --accept-commands
      --accept-config
      --disable-confd
  when:
    - i2_connection_allowed
    - i2_connection_direction == 'bottom-up'
    - not i2_certificate_signed_by_ca
    - endpoints is defined
  notify: restart icinga2
