---
- name: IcingaWeb2 (CentOs) - Install Centos Release SCL
  become: yes
  package:
    name: centos-release-scl
    state: present
  when: ansible_distribution == "CentOS"

- name: IcingaWeb2 (RedHat) - Install RhScl subscription requirement
  fail:
    msg: "Please enable SCL repos: subscription-manager repos --enable rhel-server-rhscl-{{ ansible_facts.ansible_distribution_major_version }}-rpms"
  when: ansible_distribution == "RedHat"

# We're installing httpd from base because icingaweb2's
# configuration files are also installed into the default
# configuration location in /etc/httpd/
- name: IcingaWeb2 (RedHat) - Install PHP fpm and mysqlnd
  become: yes
  yum:
    name:
      - httpd
      - rh-php72-php-fpm
      - rh-php72-php-mysqlnd
    state: present
    update_cache: yes
    enablerepo:
      - base
      - centos-sclo-rh

- name: Icingaweb2 (RedHat) - Install additional PHP modules
  become: yes
  yum:
    name:
      - rh-php72-php-ldap
      - rh-php72-php-intl
      - rh-php72-php-gd
      - rh-php72-php-dom
      - rh-php72-php-imagick
    state: present
    enablerepo:
      - centos-sclo-rh
  when: i2_webui_php_all

- name: IcingaWeb2 (RedHat) - Replace timezone in php.ini
  become: yes
  register: lineinfile
  lineinfile:
    path: /etc/opt/rh/rh-php72/php.ini
    regexp: '^;?date.timezone ='
    line: 'date.timezone = "{{ i2_timezone }}"'
  notify: restart php-fpm

- name: IcingaWeb2 (RedHat) - Install IcingaWeb2 on RedHat OS family
  become: yes
  yum:
    name:
        - icingaweb2
        - icingacli
        - git
    state: latest
    enablerepo:
      - base
      - ICINGA-release
    update_cache: yes
  tags: icinga2-ansible-web2-ui-install

- name: IcingaWeb2 (RedHat) - Install SELinux policies for Icingaweb2
  become: yes
  yum:
    name: icingaweb2-selinux
    state: latest
    enablerepo: ICINGA-release
  when: selinux.stdout == "Enforcing"

- name: "RedHat - Firewalld: allow connections to httpd"
  become: yes
  firewalld:
    zone: public
    service: http
    state: enabled
    permanent: yes
    immediate: yes
  when: i2_manage_firewall


- name: "RedHat - Firewalld: allow connections to httpd"
  become: yes
  firewalld:
    zone: public
    service: https
    state: enabled
    permanent: yes
    immediate: yes
  when: i2_manage_firewall

- name: Icingaweb2 - Ensure httpd is running
  command: /usr/bin/true
  notify: restart redhat httpd

